# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorMainView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AkCalculatorMainView(object):
    def setupUi(self, AkCalculatorMainView):
        AkCalculatorMainView.setObjectName("AkCalculatorMainView")
        AkCalculatorMainView.resize(804, 551)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AkCalculatorMainView.sizePolicy().hasHeightForWidth())
        AkCalculatorMainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(AkCalculatorMainView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hBoxCalculate = QtWidgets.QHBoxLayout()
        self.hBoxCalculate.setObjectName("hBoxCalculate")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculate.setObjectName("btnCalculate")
        self.hBoxCalculate.addWidget(self.btnCalculate, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.hBoxCalculate)
        self.notebook = QtWidgets.QTabWidget(self.centralwidget)
        self.notebook.setToolTip("")
        self.notebook.setStyleSheet("")
        self.notebook.setObjectName("notebook")
        self.tabSummary = QtWidgets.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.notebook.addTab(self.tabSummary, "")
        self.tabGraphs = QtWidgets.QWidget()
        self.tabGraphs.setObjectName("tabGraphs")
        self.notebook.addTab(self.tabGraphs, "")
        self.tabJournal = QtWidgets.QWidget()
        self.tabJournal.setObjectName("tabJournal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabJournal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hBoxTop = QtWidgets.QHBoxLayout()
        self.hBoxTop.setObjectName("hBoxTop")
        self.hBoxCalendar = QtWidgets.QVBoxLayout()
        self.hBoxCalendar.setObjectName("hBoxCalendar")
        self.calendar = QtWidgets.QCalendarWidget(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setObjectName("calendar")
        self.hBoxCalendar.addWidget(self.calendar)
        self.hBoxButtonsOKClear = QtWidgets.QHBoxLayout()
        self.hBoxButtonsOKClear.setObjectName("hBoxButtonsOKClear")
        self.btnOK = QtWidgets.QPushButton(self.tabJournal)
        self.btnOK.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOK.sizePolicy().hasHeightForWidth())
        self.btnOK.setSizePolicy(sizePolicy)
        self.btnOK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnOK.setObjectName("btnOK")
        self.hBoxButtonsOKClear.addWidget(self.btnOK)
        self.btnClear = QtWidgets.QPushButton(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.hBoxButtonsOKClear.addWidget(self.btnClear)
        self.hBoxCalendar.addLayout(self.hBoxButtonsOKClear)
        self.hBoxTop.addLayout(self.hBoxCalendar)
        self.textNote = QtWidgets.QTextEdit(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textNote.sizePolicy().hasHeightForWidth())
        self.textNote.setSizePolicy(sizePolicy)
        self.textNote.setObjectName("textNote")
        self.hBoxTop.addWidget(self.textNote)
        self.hBoxTop.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.hBoxTop)
        self.listNotes = QtWidgets.QListWidget(self.tabJournal)
        self.listNotes.setObjectName("listNotes")
        self.verticalLayout_3.addWidget(self.listNotes)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.notebook.addTab(self.tabJournal, "")
        self.verticalLayout.addWidget(self.notebook)
        AkCalculatorMainView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AkCalculatorMainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPanels = QtWidgets.QMenu(self.menuView)
        self.menuPanels.setObjectName("menuPanels")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AkCalculatorMainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AkCalculatorMainView)
        self.statusbar.setObjectName("statusbar")
        AkCalculatorMainView.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(AkCalculatorMainView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/menu/help.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(AkCalculatorMainView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu/about.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConnect = QtWidgets.QAction(AkCalculatorMainView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/menu/connect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon2)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(AkCalculatorMainView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/menu/disconnect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon3)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionExit = QtWidgets.QAction(AkCalculatorMainView)
        self.actionExit.setObjectName("actionExit")
        self.actionInstrumentView = QtWidgets.QAction(AkCalculatorMainView)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/menu/instruments.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInstrumentView.setIcon(icon4)
        self.actionInstrumentView.setObjectName("actionInstrumentView")
        self.actionHistoricalView = QtWidgets.QAction(AkCalculatorMainView)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/menu/history.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHistoricalView.setIcon(icon5)
        self.actionHistoricalView.setObjectName("actionHistoricalView")
        self.actionConnectionsView = QtWidgets.QAction(AkCalculatorMainView)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/menu/connections.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectionsView.setIcon(icon6)
        self.actionConnectionsView.setObjectName("actionConnectionsView")
        self.actionOptionsView = QtWidgets.QAction(AkCalculatorMainView)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/menu/options.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptionsView.setIcon(icon7)
        self.actionOptionsView.setObjectName("actionOptionsView")
        self.actionSummary = QtWidgets.QAction(AkCalculatorMainView)
        self.actionSummary.setObjectName("actionSummary")
        self.actionGraphs = QtWidgets.QAction(AkCalculatorMainView)
        self.actionGraphs.setObjectName("actionGraphs")
        self.actionJournal = QtWidgets.QAction(AkCalculatorMainView)
        self.actionJournal.setObjectName("actionJournal")
        self.actionJidem_na_Samui = QtWidgets.QAction(AkCalculatorMainView)
        self.actionJidem_na_Samui.setObjectName("actionJidem_na_Samui")
        self.actionNeeeee = QtWidgets.QAction(AkCalculatorMainView)
        self.actionNeeeee.setObjectName("actionNeeeee")
        self.actionJoy = QtWidgets.QAction(AkCalculatorMainView)
        self.actionJoy.setObjectName("actionJoy")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionDisconnect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionInstrumentView)
        self.menuTools.addAction(self.actionHistoricalView)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionConnectionsView)
        self.menuTools.addAction(self.actionOptionsView)
        self.menuPanels.addAction(self.actionSummary)
        self.menuPanels.addAction(self.actionGraphs)
        self.menuPanels.addAction(self.actionJournal)
        self.menuView.addAction(self.menuPanels.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AkCalculatorMainView)
        self.notebook.setCurrentIndex(0)
        self.btnOK.released.connect(self.listNotes.update)
        self.btnOK.clicked.connect(self.calendar.showSelectedDate)
        self.btnClear.clicked.connect(self.textNote.clear)
        self.btnOK.clicked.connect(self.textNote.copy)
        QtCore.QMetaObject.connectSlotsByName(AkCalculatorMainView)
        AkCalculatorMainView.setTabOrder(self.btnCalculate, self.notebook)

    def retranslateUi(self, AkCalculatorMainView):
        _translate = QtCore.QCoreApplication.translate
        AkCalculatorMainView.setWindowTitle(_translate("AkCalculatorMainView", "MainWindow"))
        self.btnCalculate.setText(_translate("AkCalculatorMainView", "Calculate"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabSummary), _translate("AkCalculatorMainView", "Summary"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabGraphs), _translate("AkCalculatorMainView", "Graphs"))
        self.btnOK.setText(_translate("AkCalculatorMainView", "OK"))
        self.btnClear.setText(_translate("AkCalculatorMainView", "Clear"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabJournal), _translate("AkCalculatorMainView", "Journal"))
        self.menuFile.setTitle(_translate("AkCalculatorMainView", "&File"))
        self.menuTools.setTitle(_translate("AkCalculatorMainView", "&Tools"))
        self.menuView.setTitle(_translate("AkCalculatorMainView", "&View"))
        self.menuPanels.setTitle(_translate("AkCalculatorMainView", "Panels"))
        self.menuHelp.setTitle(_translate("AkCalculatorMainView", "Help"))
        self.actionHelp.setText(_translate("AkCalculatorMainView", "Help"))
        self.actionHelp.setShortcut(_translate("AkCalculatorMainView", "F1"))
        self.actionAbout.setText(_translate("AkCalculatorMainView", "About"))
        self.actionConnect.setText(_translate("AkCalculatorMainView", "Connect..."))
        self.actionDisconnect.setText(_translate("AkCalculatorMainView", "Disconnect..."))
        self.actionExit.setText(_translate("AkCalculatorMainView", "Exit"))
        self.actionExit.setShortcut(_translate("AkCalculatorMainView", "Ctrl+Q"))
        self.actionInstrumentView.setText(_translate("AkCalculatorMainView", "Instrument Manager..."))
        self.actionInstrumentView.setShortcut(_translate("AkCalculatorMainView", "Ctrl+I"))
        self.actionHistoricalView.setText(_translate("AkCalculatorMainView", "Historical Data Manager..."))
        self.actionHistoricalView.setShortcut(_translate("AkCalculatorMainView", "Ctrl+H"))
        self.actionConnectionsView.setText(_translate("AkCalculatorMainView", "Connection Manager..."))
        self.actionOptionsView.setText(_translate("AkCalculatorMainView", "Options..."))
        self.actionOptionsView.setShortcut(_translate("AkCalculatorMainView", "Ctrl+O"))
        self.actionSummary.setText(_translate("AkCalculatorMainView", "Summary"))
        self.actionGraphs.setText(_translate("AkCalculatorMainView", "Graphs"))
        self.actionJournal.setText(_translate("AkCalculatorMainView", "Journal"))
        self.actionJidem_na_Samui.setText(_translate("AkCalculatorMainView", "Jidem na Samui"))
        self.actionNeeeee.setText(_translate("AkCalculatorMainView", "Neeeee"))
        self.actionJoy.setText(_translate("AkCalculatorMainView", "Joy"))

import src.resources.menuIcons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AkCalculatorMainView = QtWidgets.QMainWindow()
    ui = Ui_AkCalculatorMainView()
    ui.setupUi(AkCalculatorMainView)
    AkCalculatorMainView.show()
    sys.exit(app.exec_())

