# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorMainView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalculatorMainView(object):
    def setupUi(self, CalculatorMainView):
        CalculatorMainView.setObjectName("CalculatorMainView")
        CalculatorMainView.resize(1097, 581)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculatorMainView.sizePolicy().hasHeightForWidth())
        CalculatorMainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(CalculatorMainView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hBoxCalculate = QtWidgets.QHBoxLayout()
        self.hBoxCalculate.setObjectName("hBoxCalculate")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCalculate.sizePolicy().hasHeightForWidth())
        self.btnCalculate.setSizePolicy(sizePolicy)
        self.btnCalculate.setObjectName("btnCalculate")
        self.hBoxCalculate.addWidget(self.btnCalculate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hBoxCalculate.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.hBoxCalculate)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.instrumentsListView = QtWidgets.QListView(self.layoutWidget)
        self.instrumentsListView.setObjectName("instrumentsListView")
        self.verticalLayout.addWidget(self.instrumentsListView)
        self.notebook = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notebook.sizePolicy().hasHeightForWidth())
        self.notebook.setSizePolicy(sizePolicy)
        self.notebook.setToolTip("")
        self.notebook.setStyleSheet("")
        self.notebook.setObjectName("notebook")
        self.tabSummary = QtWidgets.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabSummary)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.instrumentsTreeView = QtWidgets.QTreeView(self.tabSummary)
        self.instrumentsTreeView.setObjectName("instrumentsTreeView")
        self.horizontalLayout_3.addWidget(self.instrumentsTreeView)
        self.ohlcTableView = QtWidgets.QTableView(self.tabSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ohlcTableView.sizePolicy().hasHeightForWidth())
        self.ohlcTableView.setSizePolicy(sizePolicy)
        self.ohlcTableView.setObjectName("ohlcTableView")
        self.ohlcTableView.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_3.addWidget(self.ohlcTableView)
        self.notebook.addTab(self.tabSummary, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 10, 91, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(280, 10, 91, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(23, 12, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(227, 12, 41, 16))
        self.label_3.setObjectName("label_3")
        self.notebook.addTab(self.tab_3, "")
        self.tabDistributions = QtWidgets.QWidget()
        self.tabDistributions.setObjectName("tabDistributions")
        self.comboBox = QtWidgets.QComboBox(self.tabDistributions)
        self.comboBox.setGeometry(QtCore.QRect(80, 10, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tabDistributions)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tabDistributions)
        self.pushButton.setGeometry(QtCore.QRect(240, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.tabDistributions)
        self.tabWidget.setGeometry(QtCore.QRect(16, 60, 771, 371))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.distributionsTableView = AkTableView(self.tab)
        self.distributionsTableView.setGeometry(QtCore.QRect(0, 0, 371, 331))
        self.distributionsTableView.setObjectName("distributionsTableView")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(380, 10, 381, 321))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.notebook.addTab(self.tabDistributions, "")
        self.tabGraphs = QtWidgets.QWidget()
        self.tabGraphs.setObjectName("tabGraphs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabGraphs)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = PlotWidget(self.tabGraphs)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.notebook.addTab(self.tabGraphs, "")
        self.tabJournal = QtWidgets.QWidget()
        self.tabJournal.setObjectName("tabJournal")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabJournal)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calendar = QtWidgets.QCalendarWidget(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setObjectName("calendar")
        self.verticalLayout_3.addWidget(self.calendar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnOK = QtWidgets.QPushButton(self.tabJournal)
        self.btnOK.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOK.sizePolicy().hasHeightForWidth())
        self.btnOK.setSizePolicy(sizePolicy)
        self.btnOK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_4.addWidget(self.btnOK)
        self.btnClear = QtWidgets.QPushButton(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_4.addWidget(self.btnClear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.textNote = QtWidgets.QTextEdit(self.tabJournal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textNote.sizePolicy().hasHeightForWidth())
        self.textNote.setSizePolicy(sizePolicy)
        self.textNote.setObjectName("textNote")
        self.horizontalLayout_5.addWidget(self.textNote)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.notesTableView = AkTableView(self.tabJournal)
        self.notesTableView.setObjectName("notesTableView")
        self.verticalLayout_4.addWidget(self.notesTableView)
        self.verticalLayout_4.setStretch(1, 3)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.notebook.addTab(self.tabJournal, "")
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        CalculatorMainView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalculatorMainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPanels = QtWidgets.QMenu(self.menuView)
        self.menuPanels.setObjectName("menuPanels")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        CalculatorMainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalculatorMainView)
        self.statusbar.setObjectName("statusbar")
        CalculatorMainView.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(CalculatorMainView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/menu/help.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(CalculatorMainView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu/about.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConnect = QtWidgets.QAction(CalculatorMainView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/menu/connect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon2)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(CalculatorMainView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/menu/disconnect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon3)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionExit = QtWidgets.QAction(CalculatorMainView)
        self.actionExit.setObjectName("actionExit")
        self.actionInstrumentView = QtWidgets.QAction(CalculatorMainView)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/menu/instruments.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInstrumentView.setIcon(icon4)
        self.actionInstrumentView.setObjectName("actionInstrumentView")
        self.actionHistoricalView = QtWidgets.QAction(CalculatorMainView)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/menu/history.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHistoricalView.setIcon(icon5)
        self.actionHistoricalView.setObjectName("actionHistoricalView")
        self.actionConnectionsView = QtWidgets.QAction(CalculatorMainView)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/menu/connections.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectionsView.setIcon(icon6)
        self.actionConnectionsView.setObjectName("actionConnectionsView")
        self.actionOptionsView = QtWidgets.QAction(CalculatorMainView)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/menu/options.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptionsView.setIcon(icon7)
        self.actionOptionsView.setObjectName("actionOptionsView")
        self.actionSummary = QtWidgets.QAction(CalculatorMainView)
        self.actionSummary.setObjectName("actionSummary")
        self.actionGraphs = QtWidgets.QAction(CalculatorMainView)
        self.actionGraphs.setObjectName("actionGraphs")
        self.actionJournal = QtWidgets.QAction(CalculatorMainView)
        self.actionJournal.setObjectName("actionJournal")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionDisconnect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionInstrumentView)
        self.menuTools.addAction(self.actionHistoricalView)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionConnectionsView)
        self.menuTools.addAction(self.actionOptionsView)
        self.menuPanels.addAction(self.actionSummary)
        self.menuPanels.addAction(self.actionGraphs)
        self.menuPanels.addAction(self.actionJournal)
        self.menuView.addAction(self.menuPanels.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CalculatorMainView)
        self.notebook.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.btnOK.clicked.connect(self.calendar.showSelectedDate)
        self.btnClear.clicked.connect(self.textNote.clear)
        self.btnOK.clicked.connect(self.textNote.copy)
        QtCore.QMetaObject.connectSlotsByName(CalculatorMainView)

    def retranslateUi(self, CalculatorMainView):
        _translate = QtCore.QCoreApplication.translate
        CalculatorMainView.setWindowTitle(_translate("CalculatorMainView", "MainWindow"))
        self.btnCalculate.setText(_translate("CalculatorMainView", "Calculate"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabSummary), _translate("CalculatorMainView", "Summary"))
        self.comboBox_2.setItemText(0, _translate("CalculatorMainView", "Day"))
        self.comboBox_2.setItemText(1, _translate("CalculatorMainView", "Week"))
        self.comboBox_2.setItemText(2, _translate("CalculatorMainView", "Month"))
        self.comboBox_2.setItemText(3, _translate("CalculatorMainView", "Quarter"))
        self.comboBox_2.setItemText(4, _translate("CalculatorMainView", "Year"))
        self.label_2.setText(_translate("CalculatorMainView", "Sector"))
        self.label_3.setText(_translate("CalculatorMainView", "Period"))
        self.notebook.setTabText(self.notebook.indexOf(self.tab_3), _translate("CalculatorMainView", "Period Converter"))
        self.label.setText(_translate("CalculatorMainView", "Serialities"))
        self.pushButton.setText(_translate("CalculatorMainView", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CalculatorMainView", "Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CalculatorMainView", "Histogram"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabDistributions), _translate("CalculatorMainView", "Amplitudes"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabGraphs), _translate("CalculatorMainView", "Graphs"))
        self.btnOK.setText(_translate("CalculatorMainView", "OK"))
        self.btnClear.setText(_translate("CalculatorMainView", "Clear"))
        self.notebook.setTabText(self.notebook.indexOf(self.tabJournal), _translate("CalculatorMainView", "Journal"))
        self.menuFile.setTitle(_translate("CalculatorMainView", "&File"))
        self.menuTools.setTitle(_translate("CalculatorMainView", "&Tools"))
        self.menuView.setTitle(_translate("CalculatorMainView", "&View"))
        self.menuPanels.setTitle(_translate("CalculatorMainView", "Panels"))
        self.menuHelp.setTitle(_translate("CalculatorMainView", "Help"))
        self.actionHelp.setText(_translate("CalculatorMainView", "Help"))
        self.actionHelp.setShortcut(_translate("CalculatorMainView", "F1"))
        self.actionAbout.setText(_translate("CalculatorMainView", "About"))
        self.actionConnect.setText(_translate("CalculatorMainView", "Connect..."))
        self.actionDisconnect.setText(_translate("CalculatorMainView", "Disconnect..."))
        self.actionExit.setText(_translate("CalculatorMainView", "Exit"))
        self.actionExit.setShortcut(_translate("CalculatorMainView", "Ctrl+Q"))
        self.actionInstrumentView.setText(_translate("CalculatorMainView", "Instrument Manager..."))
        self.actionInstrumentView.setShortcut(_translate("CalculatorMainView", "Ctrl+I"))
        self.actionHistoricalView.setText(_translate("CalculatorMainView", "Historical Data Manager..."))
        self.actionHistoricalView.setShortcut(_translate("CalculatorMainView", "Ctrl+H"))
        self.actionConnectionsView.setText(_translate("CalculatorMainView", "Connection Manager..."))
        self.actionOptionsView.setText(_translate("CalculatorMainView", "Options..."))
        self.actionOptionsView.setShortcut(_translate("CalculatorMainView", "Ctrl+O"))
        self.actionSummary.setText(_translate("CalculatorMainView", "Summary"))
        self.actionGraphs.setText(_translate("CalculatorMainView", "Graphs"))
        self.actionJournal.setText(_translate("CalculatorMainView", "Journal"))

from pyqtgraph import PlotWidget
from src.controls.akTableView import AkTableView
import src.Resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalculatorMainView = QtWidgets.QMainWindow()
    ui = Ui_CalculatorMainView()
    ui.setupUi(CalculatorMainView)
    CalculatorMainView.show()
    sys.exit(app.exec_())

