# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorMainView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalculatorMainView(object):
    def setupUi(self, CalculatorMainView):
        CalculatorMainView.setObjectName("CalculatorMainView")
        CalculatorMainView.resize(895, 555)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalculatorMainView.sizePolicy().hasHeightForWidth())
        CalculatorMainView.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(CalculatorMainView)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.left_vbox = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.left_vbox.setContentsMargins(0, 0, 0, 0)
        self.left_vbox.setObjectName("left_vbox")
        self.search_instrument = QtWidgets.QLineEdit(self.layoutWidget)
        self.search_instrument.setObjectName("search_instrument")
        self.left_vbox.addWidget(self.search_instrument)
        self.instruments_list_view = QtWidgets.QListView(self.layoutWidget)
        self.instruments_list_view.setObjectName("instruments_list_view")
        self.left_vbox.addWidget(self.instruments_list_view)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.right_vbox = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.right_vbox.setContentsMargins(0, 0, 0, 0)
        self.right_vbox.setObjectName("right_vbox")
        self.hbox_calculate = QtWidgets.QHBoxLayout()
        self.hbox_calculate.setObjectName("hbox_calculate")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_calculate.addItem(spacerItem)
        self.calculate_button = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_button.sizePolicy().hasHeightForWidth())
        self.calculate_button.setSizePolicy(sizePolicy)
        self.calculate_button.setObjectName("calculate_button")
        self.hbox_calculate.addWidget(self.calculate_button)
        self.right_vbox.addLayout(self.hbox_calculate)
        self.notebook = QtWidgets.QTabWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notebook.sizePolicy().hasHeightForWidth())
        self.notebook.setSizePolicy(sizePolicy)
        self.notebook.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notebook.setToolTip("")
        self.notebook.setStyleSheet("")
        self.notebook.setObjectName("notebook")
        self.graphs_tab = QtWidgets.QWidget()
        self.graphs_tab.setObjectName("graphs_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.graphs_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphics_table = PlotWidget(self.graphs_tab)
        self.graphics_table.setObjectName("graphics_table")
        self.verticalLayout_2.addWidget(self.graphics_table)
        self.notebook.addTab(self.graphs_tab, "")
        self.journal_tab = QtWidgets.QWidget()
        self.journal_tab.setObjectName("journal_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.journal_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.vbox_journal = QtWidgets.QVBoxLayout()
        self.vbox_journal.setObjectName("vbox_journal")
        self.hbox_note = QtWidgets.QHBoxLayout()
        self.hbox_note.setObjectName("hbox_note")
        self.vbox_calendar = QtWidgets.QVBoxLayout()
        self.vbox_calendar.setObjectName("vbox_calendar")
        self.journal_calendar = QtWidgets.QCalendarWidget(self.journal_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journal_calendar.sizePolicy().hasHeightForWidth())
        self.journal_calendar.setSizePolicy(sizePolicy)
        self.journal_calendar.setObjectName("journal_calendar")
        self.vbox_calendar.addWidget(self.journal_calendar)
        self.hbox_buttons = QtWidgets.QHBoxLayout()
        self.hbox_buttons.setObjectName("hbox_buttons")
        self.journal_ok_button = QtWidgets.QPushButton(self.journal_tab)
        self.journal_ok_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journal_ok_button.sizePolicy().hasHeightForWidth())
        self.journal_ok_button.setSizePolicy(sizePolicy)
        self.journal_ok_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.journal_ok_button.setObjectName("journal_ok_button")
        self.hbox_buttons.addWidget(self.journal_ok_button)
        self.journal_clear_button = QtWidgets.QPushButton(self.journal_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journal_clear_button.sizePolicy().hasHeightForWidth())
        self.journal_clear_button.setSizePolicy(sizePolicy)
        self.journal_clear_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.journal_clear_button.setObjectName("journal_clear_button")
        self.hbox_buttons.addWidget(self.journal_clear_button)
        self.vbox_calendar.addLayout(self.hbox_buttons)
        self.hbox_note.addLayout(self.vbox_calendar)
        self.journal_text_note = QtWidgets.QTextEdit(self.journal_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journal_text_note.sizePolicy().hasHeightForWidth())
        self.journal_text_note.setSizePolicy(sizePolicy)
        self.journal_text_note.setObjectName("journal_text_note")
        self.hbox_note.addWidget(self.journal_text_note)
        self.vbox_journal.addLayout(self.hbox_note)
        self.journal_notes_table = AkTableView(self.journal_tab)
        self.journal_notes_table.setObjectName("journal_notes_table")
        self.vbox_journal.addWidget(self.journal_notes_table)
        self.vbox_journal.setStretch(1, 3)
        self.verticalLayout_8.addLayout(self.vbox_journal)
        self.notebook.addTab(self.journal_tab, "")
        self.right_vbox.addWidget(self.notebook)
        self.horizontalLayout.addWidget(self.splitter)
        CalculatorMainView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalculatorMainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.action_new_analysis = QtWidgets.QMenu(self.menu_file)
        self.action_new_analysis.setObjectName("action_new_analysis")
        self.menu_tools = QtWidgets.QMenu(self.menubar)
        self.menu_tools.setObjectName("menu_tools")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        CalculatorMainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalculatorMainView)
        self.statusbar.setObjectName("statusbar")
        CalculatorMainView.setStatusBar(self.statusbar)
        self.action_help = QtWidgets.QAction(CalculatorMainView)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/menu/help.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_help.setIcon(icon)
        self.action_help.setObjectName("action_help")
        self.action_about = QtWidgets.QAction(CalculatorMainView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menu/about.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon1)
        self.action_about.setObjectName("action_about")
        self.action_connect = QtWidgets.QAction(CalculatorMainView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/menu/connect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_connect.setIcon(icon2)
        self.action_connect.setObjectName("action_connect")
        self.action_disconnect = QtWidgets.QAction(CalculatorMainView)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/menu/disconnect.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_disconnect.setIcon(icon3)
        self.action_disconnect.setObjectName("action_disconnect")
        self.action_exit = QtWidgets.QAction(CalculatorMainView)
        self.action_exit.setObjectName("action_exit")
        self.action_instruments_view = QtWidgets.QAction(CalculatorMainView)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/menu/instruments.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_instruments_view.setIcon(icon4)
        self.action_instruments_view.setObjectName("action_instruments_view")
        self.action_historical_view = QtWidgets.QAction(CalculatorMainView)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/menu/history.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_historical_view.setIcon(icon5)
        self.action_historical_view.setObjectName("action_historical_view")
        self.action_connections_view = QtWidgets.QAction(CalculatorMainView)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/menu/connections.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_connections_view.setIcon(icon6)
        self.action_connections_view.setObjectName("action_connections_view")
        self.action_options_view = QtWidgets.QAction(CalculatorMainView)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/menu/options.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_options_view.setIcon(icon7)
        self.action_options_view.setObjectName("action_options_view")
        self.actionSummary = QtWidgets.QAction(CalculatorMainView)
        self.actionSummary.setObjectName("actionSummary")
        self.actionGraphs = QtWidgets.QAction(CalculatorMainView)
        self.actionGraphs.setObjectName("actionGraphs")
        self.actionJournal = QtWidgets.QAction(CalculatorMainView)
        self.actionJournal.setObjectName("actionJournal")
        self.action_create_analysis = QtWidgets.QAction(CalculatorMainView)
        self.action_create_analysis.setObjectName("action_create_analysis")
        self.action_calculator = QtWidgets.QAction(CalculatorMainView)
        self.action_calculator.setObjectName("action_calculator")
        self.action_analysis = QtWidgets.QAction(CalculatorMainView)
        self.action_analysis.setObjectName("action_analysis")
        self.action_series_analysis = QtWidgets.QAction(CalculatorMainView)
        self.action_series_analysis.setObjectName("action_series_analysis")
        self.action_combinations_analysis = QtWidgets.QAction(CalculatorMainView)
        self.action_combinations_analysis.setObjectName("action_combinations_analysis")
        self.action_statistic_analysis = QtWidgets.QAction(CalculatorMainView)
        self.action_statistic_analysis.setObjectName("action_statistic_analysis")
        self.action_settings = QtWidgets.QAction(CalculatorMainView)
        self.action_settings.setObjectName("action_settings")
        self.action_new_analysis.addAction(self.action_analysis)
        self.menu_file.addAction(self.action_new_analysis.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_connect)
        self.menu_file.addAction(self.action_disconnect)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_tools.addAction(self.action_instruments_view)
        self.menu_tools.addAction(self.action_historical_view)
        self.menu_tools.addSeparator()
        self.menu_tools.addAction(self.action_connections_view)
        self.menu_tools.addAction(self.action_options_view)
        self.menu_view.addAction(self.action_statistic_analysis)
        self.menu_view.addAction(self.action_create_analysis)
        self.menu_view.addAction(self.action_calculator)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_series_analysis)
        self.menu_view.addAction(self.action_combinations_analysis)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_settings)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_tools.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(CalculatorMainView)
        self.notebook.setCurrentIndex(0)
        self.journal_ok_button.clicked.connect(self.journal_calendar.showSelectedDate)
        self.journal_clear_button.clicked.connect(self.journal_text_note.clear)
        self.journal_ok_button.clicked.connect(self.journal_text_note.copy)
        QtCore.QMetaObject.connectSlotsByName(CalculatorMainView)

    def retranslateUi(self, CalculatorMainView):
        _translate = QtCore.QCoreApplication.translate
        CalculatorMainView.setWindowTitle(_translate("CalculatorMainView", "MainWindow"))
        self.calculate_button.setText(_translate("CalculatorMainView", "Calculate"))
        self.notebook.setTabText(self.notebook.indexOf(self.graphs_tab), _translate("CalculatorMainView", "Graphs"))
        self.journal_ok_button.setText(_translate("CalculatorMainView", "OK"))
        self.journal_clear_button.setText(_translate("CalculatorMainView", "Clear"))
        self.notebook.setTabText(self.notebook.indexOf(self.journal_tab), _translate("CalculatorMainView", "Journal"))
        self.menu_file.setTitle(_translate("CalculatorMainView", "&File"))
        self.action_new_analysis.setTitle(_translate("CalculatorMainView", "New..."))
        self.menu_tools.setTitle(_translate("CalculatorMainView", "&Tools"))
        self.menu_view.setTitle(_translate("CalculatorMainView", "&Analysis"))
        self.menu_help.setTitle(_translate("CalculatorMainView", "Help"))
        self.action_help.setText(_translate("CalculatorMainView", "Help"))
        self.action_help.setShortcut(_translate("CalculatorMainView", "F1"))
        self.action_about.setText(_translate("CalculatorMainView", "About"))
        self.action_connect.setText(_translate("CalculatorMainView", "Connect..."))
        self.action_disconnect.setText(_translate("CalculatorMainView", "Disconnect..."))
        self.action_exit.setText(_translate("CalculatorMainView", "Exit"))
        self.action_exit.setShortcut(_translate("CalculatorMainView", "Ctrl+Q"))
        self.action_instruments_view.setText(_translate("CalculatorMainView", "Instrument Manager..."))
        self.action_instruments_view.setShortcut(_translate("CalculatorMainView", "Ctrl+I"))
        self.action_historical_view.setText(_translate("CalculatorMainView", "Historical Data Manager..."))
        self.action_historical_view.setShortcut(_translate("CalculatorMainView", "Ctrl+H"))
        self.action_connections_view.setText(_translate("CalculatorMainView", "Connection Manager..."))
        self.action_options_view.setText(_translate("CalculatorMainView", "Options..."))
        self.action_options_view.setShortcut(_translate("CalculatorMainView", "Ctrl+O"))
        self.actionSummary.setText(_translate("CalculatorMainView", "Summary"))
        self.actionGraphs.setText(_translate("CalculatorMainView", "Graphs"))
        self.actionJournal.setText(_translate("CalculatorMainView", "Journal"))
        self.action_create_analysis.setText(_translate("CalculatorMainView", "Calendar"))
        self.action_calculator.setText(_translate("CalculatorMainView", "Periods"))
        self.action_analysis.setText(_translate("CalculatorMainView", "Analysis"))
        self.action_series_analysis.setText(_translate("CalculatorMainView", "Series"))
        self.action_combinations_analysis.setText(_translate("CalculatorMainView", "Combinations"))
        self.action_statistic_analysis.setText(_translate("CalculatorMainView", "Statistic"))
        self.action_settings.setText(_translate("CalculatorMainView", "Settings..."))

from pyqtgraph import PlotWidget
from src.controls.akTableView import AkTableView
import src.Resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalculatorMainView = QtWidgets.QMainWindow()
    ui = Ui_CalculatorMainView()
    ui.setupUi(CalculatorMainView)
    CalculatorMainView.show()
    sys.exit(app.exec_())

