# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historicalView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HistoricalDialog(object):
    def setupUi(self, HistoricalDialog):
        HistoricalDialog.setObjectName("HistoricalDialog")
        HistoricalDialog.resize(773, 446)
        self.verticalLayout = QtWidgets.QVBoxLayout(HistoricalDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs_widget = QtWidgets.QTabWidget(HistoricalDialog)
        self.tabs_widget.setObjectName("tabs_widget")
        self.tab_import = QtWidgets.QWidget()
        self.tab_import.setObjectName("tab_import")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_import)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hbox_import = QtWidgets.QHBoxLayout()
        self.hbox_import.setObjectName("hbox_import")
        self.splitter = QtWidgets.QSplitter(self.tab_import)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tree_view_windows_files = QtWidgets.QTreeView(self.splitter)
        self.tree_view_windows_files.setObjectName("tree_view_windows_files")
        self.table_view_imported_data = QtWidgets.QTableView(self.splitter)
        self.table_view_imported_data.setObjectName("table_view_imported_data")
        self.hbox_import.addWidget(self.splitter)
        self.button_import_data = QtWidgets.QPushButton(self.tab_import)
        self.button_import_data.setObjectName("button_import_data")
        self.hbox_import.addWidget(self.button_import_data, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.hbox_import)
        self.tabs_widget.addTab(self.tab_import, "")
        self.tab_download = QtWidgets.QWidget()
        self.tab_download.setObjectName("tab_download")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_download)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hbox_download = QtWidgets.QHBoxLayout()
        self.hbox_download.setObjectName("hbox_download")
        self.left_vbox_download = QtWidgets.QVBoxLayout()
        self.left_vbox_download.setObjectName("left_vbox_download")
        self.lables_symbols = QtWidgets.QLabel(self.tab_download)
        self.lables_symbols.setObjectName("lables_symbols")
        self.left_vbox_download.addWidget(self.lables_symbols)
        self.hbox_search_symbol = QtWidgets.QHBoxLayout()
        self.hbox_search_symbol.setObjectName("hbox_search_symbol")
        self.line_search_symbol = QtWidgets.QLineEdit(self.tab_download)
        self.line_search_symbol.setObjectName("line_search_symbol")
        self.hbox_search_symbol.addWidget(self.line_search_symbol)
        self.hbox_delete_item = QtWidgets.QHBoxLayout()
        self.hbox_delete_item.setObjectName("hbox_delete_item")
        self.button_clear_all = QtWidgets.QToolButton(self.tab_download)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/clearall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_clear_all.setIcon(icon)
        self.button_clear_all.setObjectName("button_clear_all")
        self.hbox_delete_item.addWidget(self.button_clear_all)
        self.button_delete = QtWidgets.QToolButton(self.tab_download)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete.setIcon(icon1)
        self.button_delete.setObjectName("button_delete")
        self.hbox_delete_item.addWidget(self.button_delete)
        self.hbox_search_symbol.addLayout(self.hbox_delete_item)
        self.left_vbox_download.addLayout(self.hbox_search_symbol)
        self.list_view_imported_symbols = QtWidgets.QListView(self.tab_download)
        self.list_view_imported_symbols.setObjectName("list_view_imported_symbols")
        self.left_vbox_download.addWidget(self.list_view_imported_symbols)
        self.hbox_download.addLayout(self.left_vbox_download)
        self.right_vbox_download = QtWidgets.QVBoxLayout()
        self.right_vbox_download.setObjectName("right_vbox_download")
        self.label_database_count = QtWidgets.QLabel(self.tab_download)
        self.label_database_count.setObjectName("label_database_count")
        self.right_vbox_download.addWidget(self.label_database_count)
        self.table_view_dohlc_data = AkTableView(self.tab_download)
        self.table_view_dohlc_data.setObjectName("table_view_dohlc_data")
        self.right_vbox_download.addWidget(self.table_view_dohlc_data)
        self.gbox_filtering_data = QtWidgets.QGroupBox(self.tab_download)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_filtering_data.sizePolicy().hasHeightForWidth())
        self.gbox_filtering_data.setSizePolicy(sizePolicy)
        self.gbox_filtering_data.setMinimumSize(QtCore.QSize(200, 0))
        self.gbox_filtering_data.setObjectName("gbox_filtering_data")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gbox_filtering_data)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vbox_filtering_data = QtWidgets.QVBoxLayout()
        self.vbox_filtering_data.setObjectName("vbox_filtering_data")
        self.fbox_filter_dates = QtWidgets.QFormLayout()
        self.fbox_filter_dates.setContentsMargins(-1, -1, -1, 5)
        self.fbox_filter_dates.setHorizontalSpacing(30)
        self.fbox_filter_dates.setObjectName("fbox_filter_dates")
        self.label_start_date = QtWidgets.QLabel(self.gbox_filtering_data)
        self.label_start_date.setObjectName("label_start_date")
        self.fbox_filter_dates.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_start_date)
        self.date_start = QtWidgets.QDateEdit(self.gbox_filtering_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_start.sizePolicy().hasHeightForWidth())
        self.date_start.setSizePolicy(sizePolicy)
        self.date_start.setObjectName("date_start")
        self.fbox_filter_dates.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.date_start)
        self.label_end_date = QtWidgets.QLabel(self.gbox_filtering_data)
        self.label_end_date.setObjectName("label_end_date")
        self.fbox_filter_dates.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_end_date)
        self.date_end = QtWidgets.QDateEdit(self.gbox_filtering_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_end.sizePolicy().hasHeightForWidth())
        self.date_end.setSizePolicy(sizePolicy)
        self.date_end.setObjectName("date_end")
        self.fbox_filter_dates.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.date_end)
        self.vbox_filtering_data.addLayout(self.fbox_filter_dates)
        self.button_filter_data = QtWidgets.QPushButton(self.gbox_filtering_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_filter_data.sizePolicy().hasHeightForWidth())
        self.button_filter_data.setSizePolicy(sizePolicy)
        self.button_filter_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_filter_data.setObjectName("button_filter_data")
        self.vbox_filtering_data.addWidget(self.button_filter_data, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.vbox_filtering_data)
        self.right_vbox_download.addWidget(self.gbox_filtering_data)
        self.hbox_download.addLayout(self.right_vbox_download)
        self.hbox_download.setStretch(0, 1)
        self.hbox_download.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.hbox_download)
        self.tabs_widget.addTab(self.tab_download, "")
        self.verticalLayout.addWidget(self.tabs_widget)

        self.retranslateUi(HistoricalDialog)
        self.tabs_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HistoricalDialog)

    def retranslateUi(self, HistoricalDialog):
        _translate = QtCore.QCoreApplication.translate
        HistoricalDialog.setWindowTitle(_translate("HistoricalDialog", "Dialog"))
        self.button_import_data.setText(_translate("HistoricalDialog", "Import Data"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.tab_import), _translate("HistoricalDialog", "Import"))
        self.lables_symbols.setText(_translate("HistoricalDialog", "Symbols: "))
        self.button_clear_all.setText(_translate("HistoricalDialog", "Clear"))
        self.button_delete.setText(_translate("HistoricalDialog", "Del"))
        self.label_database_count.setText(_translate("HistoricalDialog", "Database: "))
        self.gbox_filtering_data.setTitle(_translate("HistoricalDialog", "Filter Data"))
        self.label_start_date.setText(_translate("HistoricalDialog", "Start date: "))
        self.label_end_date.setText(_translate("HistoricalDialog", "End date: "))
        self.button_filter_data.setText(_translate("HistoricalDialog", "Filter"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.tab_download), _translate("HistoricalDialog", "Instruments"))

from src.controls.akTableView import AkTableView
import src.Resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistoricalDialog = QtWidgets.QDialog()
    ui = Ui_HistoricalDialog()
    ui.setupUi(HistoricalDialog)
    HistoricalDialog.show()
    sys.exit(app.exec_())

